
@echo off
:: =============================================================================
::  VeriSage Pro — Step 6 Onwards Runner
::  Version : 1.0
::  Run as  : Administrator
::
::  This script continues deployment from Step 6:
::    1. Interactively builds .env
::    2. Runs database migration
::    3. Starts app with PM2
::    4. Does health check
::
::  Assumes:
::    - Node.js + npm + PM2 already installed
::    - Backend is copied to C:\VeriSagePro\backend
:: =============================================================================

setlocal enabledelayedexpansion
title VeriSage Pro - Step 6 Onwards

echo.
echo  ============================================================
echo   VeriSage Pro  ^|  Step 6 Onwards Runner
echo  ============================================================
echo.

set "INSTALL_DIR=C:\VeriSagePro"
set "BACKEND_DIR=!INSTALL_DIR!\backend"
set "PUBLIC_DIR=!INSTALL_DIR!\public"
set "LOGS_DIR=!BACKEND_DIR!\logs"

if not exist "!BACKEND_DIR!" (
    echo  [ERROR] Backend directory not found: !BACKEND_DIR!
    echo          Did you run deploy.bat up to Step 5?
    pause
    exit /b 1
)

:: ── STEP 6: Set up the .env file ─────────────────────────────────────────────
echo.
echo  [6/8] Environment Configuration (.env)
echo  ============================================================
echo.

set "ENV_FILE=!BACKEND_DIR!\.env"

if exist "!ENV_FILE!" (
    echo  [WARN] A .env file already exists at:
    echo         !ENV_FILE!
    echo.
    set /p "OVERWRITE=  Overwrite existing .env? (y/n): "
    if /i "!OVERWRITE!"=="n" (
        echo  [INFO] Keeping existing .env. Proceeding...
        goto :after_env
    )
)

echo  Fill in the values below. Press ENTER to accept the default shown in [brackets].
echo.

:: ── App settings ──────────────────────────────────────────────────────────────
echo  --- Application Settings ---
set "PORT=4000"
set /p "PORT=  Port to run on [4000]: "
if "!PORT!"=="" set "PORT=4000"

set "NODE_ENV=production"
echo  NODE_ENV set to: production

:: ── VeriSage DB ───────────────────────────────────────────────────────────────
echo.
echo  --- VeriSage Pro Database (your own database, separate from SAGE) ---
set "DB_SERVER=localhost"
set /p "DB_SERVER=  SQL Server hostname or IP [localhost]: "
if "!DB_SERVER!"=="" set "DB_SERVER=localhost"

set "DB_DATABASE=VeriSagePro"
set /p "DB_DATABASE=  Database name [VeriSagePro]: "
if "!DB_DATABASE!"=="" set "DB_DATABASE=VeriSagePro"

set "DB_PORT=1433"
set /p "DB_PORT=  SQL Server port [1433]: "
if "!DB_PORT!"=="" set "DB_PORT=1433"

set "DB_USER=sa"
set /p "DB_USER=  SQL login username [sa]: "
if "!DB_USER!"=="" set "DB_USER=sa"

set /p "DB_PASSWORD=  SQL login password: "

:: ── SAGE DB ───────────────────────────────────────────────────────────────────
echo.
echo  --- SAGE 200 Evolution Database ---
set /p "SAGE_DB_SERVER=  SAGE SQL Server hostname or IP: "

set "SAGE_DB_DATABASE=SageEvolution"
set /p "SAGE_DB_DATABASE=  SAGE database name [SageEvolution]: "
if "!SAGE_DB_DATABASE!"=="" set "SAGE_DB_DATABASE=SageEvolution"

set "SAGE_DB_PORT=1433"
set /p "SAGE_DB_PORT=  SAGE SQL Server port [1433]: "
if "!SAGE_DB_PORT!"=="" set "SAGE_DB_PORT=1433"

set "SAGE_DB_USER=sa"
set /p "SAGE_DB_USER=  SAGE SQL login username [sa]: "
if "!SAGE_DB_USER!"=="" set "SAGE_DB_USER=sa"

set /p "SAGE_DB_PASSWORD=  SAGE SQL login password: "

:: ── SAGE reference IDs ────────────────────────────────────────────────────────
echo.
echo  --- SAGE Reference IDs (get these from SSMS queries in the guide) ---
set /p "SAGE_STOCK_CODE_ID=  SAGE Stock Code ID (StockLink for Registrar Services): "
set /p "SAGE_WAREHOUSE_ID=  SAGE Warehouse ID (WhseLink for default warehouse): "
set /p "SAGE_TAX_TYPE_ID=  SAGE Tax Type ID (idTaxRate for 7.5%% VAT): "

:: ── Security secrets ──────────────────────────────────────────────────────────
echo.
echo  --- Security Secrets ---
echo  [INFO] Generating a random JWT secret automatically...

set "JWT_SECRET=vsp_%RANDOM%%RANDOM%%RANDOM%%RANDOM%_%RANDOM%"
echo  [OK] JWT_SECRET generated.

set /p "COCCA_API_KEY=  CoCCA API Key (the key you will give to CoCCA): "

:: ── Frontend URL ──────────────────────────────────────────────────────────────
echo.
set "FRONTEND_URL=http://localhost:!PORT!"
echo  FRONTEND_URL set to: !FRONTEND_URL!

:: ── Write the .env file ───────────────────────────────────────────────────────
(
    echo # VeriSage Pro - Environment Configuration
    echo # Generated by step6-onwards.bat on %DATE% %TIME%
    echo.
    echo # Application
    echo PORT=!PORT!
    echo NODE_ENV=production
    echo FRONTEND_URL=!FRONTEND_URL!
    echo.
    echo # VeriSage Pro Database
    echo DB_DIALECT=mssql
    echo DB_USER=!DB_USER!
    echo DB_PASSWORD=!DB_PASSWORD!
    echo DB_SERVER=!DB_SERVER!
    echo DB_DATABASE=!DB_DATABASE!
    echo DB_PORT=!DB_PORT!
    echo.
    echo # SAGE 200 Evolution Database
    echo SAGE_DB_USER=!SAGE_DB_USER!
    echo SAGE_DB_PASSWORD=!SAGE_DB_PASSWORD!
    echo SAGE_DB_SERVER=!SAGE_DB_SERVER!
    echo SAGE_DB_DATABASE=!SAGE_DB_DATABASE!
    echo SAGE_DB_PORT=!SAGE_DB_PORT!
    echo.
    echo # SAGE Reference IDs
    echo SAGE_STOCK_CODE_ID=!SAGE_STOCK_CODE_ID!
    echo SAGE_WAREHOUSE_ID=!SAGE_WAREHOUSE_ID!
    echo SAGE_TAX_TYPE_ID=!SAGE_TAX_TYPE_ID!
    echo.
    echo # JWT Authentication
    echo JWT_SECRET=!JWT_SECRET!
    echo JWT_EXPIRES_IN=8h
    echo.
    echo # CoCCA Webhook API Key
    echo COCCA_API_KEY=!COCCA_API_KEY!
    echo.
    echo # Scheduler Settings
    echo MAX_RETRY_ATTEMPTS=3
    echo RETRY_CRON=*/5 * * * *
    echo INCOME_RECOGNITION_CRON=0 0 * * *
) > "!ENV_FILE!"

echo.
echo  [OK] .env file written to: !ENV_FILE!

:after_env

:: ── STEP 7: Run database migration ───────────────────────────────────────────
echo.
echo  [7/8] Running database migration...
echo        (Creates tables in VeriSagePro database + default admin user)
echo.
cd /d "!BACKEND_DIR!"
node src/config/migrate.js
if not !errorlevel! == 0 (
    echo.
    echo  [ERROR] Database migration failed.
    echo.
    echo  Common causes:
    echo    1. SQL Server is not running - check Services in Task Manager
    echo    2. The VeriSagePro database does not exist yet
    echo       Open SSMS, connect to !DB_SERVER!, create an empty database
    echo       named "!DB_DATABASE!", then re-run:
    echo         cd !BACKEND_DIR!
    echo         node src/config/migrate.js
    echo    3. Wrong credentials in .env - edit !ENV_FILE!
    echo    4. TCP/IP not enabled in SQL Server Configuration Manager
    echo.
    pause
    exit /b 1
)
echo.
echo  [OK] Database migration complete.

:: ── STEP 8: Start with PM2 ───────────────────────────────────────────────────
echo.
echo  [8/8] Starting VeriSage Pro with PM2...
echo.
cd /d "!BACKEND_DIR!"

:: Stop existing instance if running (ignore error if not running yet)
pm2 delete verisage-pro >nul 2>&1

:: Start fresh
pm2 start src/index.js --name verisage-pro --log "!LOGS_DIR!\pm2.log" --time
if not !errorlevel! == 0 (
    echo  [ERROR] PM2 failed to start the application.
    echo          Check the log: !LOGS_DIR!\pm2.log
    pause
    exit /b 1
)

:: Save PM2 process list so it survives reboots
pm2 save

:: Enable PM2 startup on Windows boot
echo.
echo  [INFO] Configuring PM2 to start on Windows boot...
pm2 startup
echo.
echo  [INFO] If the above output shows a command starting with "pm2",
echo         copy and paste it into this window and press ENTER.
echo         Then run:  pm2 save
echo.

:: ── Health check ─────────────────────────────────────────────────────────────
echo  Waiting 5 seconds for the server to initialise...
timeout /t 5 /nobreak >nul

echo.
echo  Checking health endpoint...
curl -s "http://localhost:!PORT!/health"
echo.

:: ── Done ─────────────────────────────────────────────────────────────────────
echo.
echo  ============================================================
echo   DEPLOYMENT COMPLETE
echo  ============================================================
echo.
echo   Dashboard URL   : http://localhost:!PORT!
echo   API Base URL    : http://localhost:!PORT!/api
echo   Health Check    : http://localhost:!PORT!/health
echo   Webhook URL     : http://localhost:!PORT!/api/webhook/topup
echo.
echo   Default login   : admin@nira.org.ng
echo   Default password: ChangeMe@2025!
echo   IMPORTANT: Change this password immediately after first login.
echo.
echo   PM2 commands:
echo     pm2 status                   - see if app is running
echo     pm2 logs verisage-pro        - live log output
echo     pm2 restart verisage-pro     - restart the app
echo     pm2 stop verisage-pro        - stop the app
echo.
echo   Log files:
echo     !LOGS_DIR!\pm2.log
echo     !LOGS_DIR!\combined.log
echo     !LOGS_DIR!\error.log
echo.
echo  ============================================================
echo.
pause
endlocal
exit /b 0
